# typed: false
# frozen_string_literal: true

# This file was generated by GitHub Actions. DO NOT EDIT.
cask "colimabar" do
  version "__VERSION__"
  sha256 "__SHA256__"

  url "https://github.com/webbhalsa/colimabar/releases/download/v#{version}/ColimaBar-#{version}.zip"
  name "ColimaBar"
  desc "Menu bar controller for colima"
  homepage "https://github.com/webbhalsa/colimabar"

  depends_on formula: "colima"
  depends_on macos: :sonoma

  app "ColimaBar.app"

  caveats <<~EOS
    ColimaBar is currently ad-hoc signed, so macOS Gatekeeper blocks
    it on first launch. Open it once by either:

      • right-clicking ColimaBar in Launchpad or Finder and choosing
        Open, then Open again in the dialog, or

      • running this in a terminal:
          xattr -d com.apple.quarantine /Applications/ColimaBar.app

    Subsequent launches work normally.

    ColimaBar wraps the `colima` CLI — installed automatically as a
    dependency of this cask.
  EOS

  zap trash: [
    "~/Library/Preferences/se.kry.ColimaBar.plist",
    "~/Library/Application Scripts/se.kry.ColimaBar",
    "~/Library/Containers/se.kry.ColimaBar",
  ]
end
