# typed: false
# frozen_string_literal: true

# This file was generated by GitHub Actions. DO NOT EDIT.
cask "colimabar" do
  version "__VERSION__"
  sha256 "__SHA256__"

  url "https://github.com/webbhalsa/colimabar/releases/download/v#{version}/ColimaBar-#{version}.zip"
  name "ColimaBar"
  desc "Menu bar controller for colima"
  homepage "https://github.com/webbhalsa/colimabar"

  depends_on formula: "colima"
  depends_on macos: ">= :sonoma"

  app "ColimaBar.app"

  zap trash: [
    "~/Library/Preferences/se.kry.ColimaBar.plist",
    "~/Library/Application Scripts/se.kry.ColimaBar",
    "~/Library/Containers/se.kry.ColimaBar",
  ]
end
